### ISSUE TITLE
Missing requirements

### ISSUE THREAD

**Issue by birnenkompott** [sarahhabershon/ankigenerator#1]
Cool project! However, the demo python script will only run after genanki and pandas are installed. A requirements.txt would be helpful.

**Comment by birnenkompott** [comment]
I have created a requirements.txt but don't seem to have the rights to push and create pull requests. Mind adding me?

**Comment by sarahhabershon** [comment]
I would love to!

**Comment by sarahhabershon** [comment]
I have invited you, did that work?
